name: Swift/MacOSX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted, macOS, x64]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and test with Maven
      run: .github/scripts/run-tests-swift.sh
      env: 
        TARGET: swift
        GROUP: LEXER
